version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

  build:
    docker:
      - image: circleci/node:14  
    steps:
      - checkout  
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: docker build -t my-react-app -t tishajain220/my-react-app:latest .
      - run:
          name: Docker Login and Push
          command: |
            echo $DOCKER_PASSWORD | docker login -u tishajain220 --password-stdin
            docker push tishajain220/my-react-app:latest

workflows:
  build:
    jobs:
      - build
      - notify:
          requires:
            - build
